<script setup lang="ts">
import {onMounted,ref,reactive} from 'vue'
import {useRoute} from 'vue-router'
import {api} from '../auth/client'
import {bindingPayload} from './model'
import {useDraft} from '../../shared/draft'
const route=useRoute(),state=reactive({rows:[] as any[]}),error=ref(''),message=ref(''),busy=ref(false),draft=useDraft(state,()=>`bindings.${route.params.id}`)
onMounted(async()=>{try{const [all,selected]=await Promise.all([api.get('/attributes'),api.get(`/categories/${route.params.id}/attributes`)]);state.rows=all.filter((a:any)=>a.status==='ACTIVE').map((a:any)=>{const current=selected.find((b:any)=>b.attributeId===a.id);return {attributeId:a.id,nameZh:a.nameZh,dataType:a.dataType,isGlobal:a.isGlobal,selected:!!current,isRequired:a.defaultRequired,isFilterable:a.defaultFilterable,showInDetail:false,sortOrder:a.sortOrder,...current}});await draft.restore()}catch(e){error.value=(e as Error).message}})
async function save(){busy.value=true;error.value='';try{await api.put(`/categories/${route.params.id}/attributes`,bindingPayload(state.rows));draft.saved();message.value='分类参数已保存。'}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><section><RouterLink to="/categories">返回分类管理</RouterLink><h1>分类参数配置</h1><p class="muted">全局参数始终可用；必填、可筛选和详情显示分别控制。</p><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="message" role="status">{{message}}</p><form class="surface" @submit.prevent="save"><div class="table-scroll"><table><thead><tr><th>参数</th><th>关联</th><th>必填</th><th>筛选</th><th>详情显示</th><th>排序</th></tr></thead><tbody><tr v-for="row in state.rows" :key="row.attributeId"><td>{{row.nameZh}}<small v-if="row.isGlobal"> · 全局</small></td><td><input type="checkbox" v-model="row.selected" :disabled="row.isGlobal" :aria-label="`关联 ${row.nameZh}`"></td><td><input type="checkbox" v-model="row.isRequired" :aria-label="`必填 ${row.nameZh}`"></td><td><input type="checkbox" v-model="row.isFilterable" :aria-label="`筛选 ${row.nameZh}`"></td><td><input type="checkbox" v-model="row.showInDetail" :aria-label="`显示 ${row.nameZh}`"></td><td><input type="number" v-model.number="row.sortOrder" min="0" :aria-label="`排序 ${row.nameZh}`" class="order-input"></td></tr></tbody></table></div><p v-if="!state.rows.length" class="muted">暂无启用的参数，请先到参数配置创建。</p><div class="form-footer"><el-button type="primary" native-type="submit" :loading="busy">保存分类参数</el-button></div></form></section></template>
