<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import EnglishReview from '../translation/EnglishReview.vue'
import {api} from '../auth/client'
import {contentDefaults,contentLabels,unwrapContent} from './model'
import {flattenCategories,englishNames,statusNames} from '../products/model'
import FormFields from '../../shared/FormFields.vue'
import RichTextEditor from '../../shared/RichTextEditor.vue'
import MediaField from '../../shared/MediaField.vue'
import type {Field} from '../../shared/fields'
import {confirmAction} from '../../shared/confirm'
import {useDraft} from '../../shared/draft'
const route=useRoute(),router=useRouter(),kind=computed(()=>String(route.meta.kind)),model=reactive<Record<string,any>>(contentDefaults(kind.value)),locale=ref('Zh'),categories=ref<any[]>([]),products=ref<any[]>([]),ready=ref(false),busy=ref(false),error=ref(''),message=ref(''),form=ref<HTMLFormElement>()
const draft=useDraft(model,()=>`${kind.value}.${route.params.id}`)
const shared=computed<Field[]>(()=>[
 ...(['articles','cases'].includes(kind.value)?[{key:'slug',label:'网址标识',required:true,pattern:'[a-z0-9]+(-[a-z0-9]+)*'}]:[]),
 ...(kind.value==='articles'?[{key:'categoryId',label:'文章分类',type:'select',required:true,options:[{value:null,label:'选择分类'},...categories.value.map(c=>({value:c.id,label:c.nameZh}))]}]:[]),
 ...(kind.value!=='certificates'?[{key:'languageMode',label:'语言范围',type:'select',options:[{value:'ZH_ONLY',label:'仅中文'},{value:'EN_ONLY',label:'仅英文'},{value:'BILINGUAL',label:'中英双语'}]}]:[{key:'type',label:'证书 / 资料类型',required:true,max:64}]),
 ...(kind.value==='catalogs'?[{key:'version',label:'目录版本',required:true,max:100}]:[{key:'sortOrder',label:'排序',type:'number'},{key:'isFeatured',label:'首页精选',type:'checkbox'}]),
 ...(kind.value==='certificates'?[{key:'isPublic',label:'公开展示',type:'checkbox'},{key:'allowDownload',label:'允许下载',type:'checkbox'}]:[])
])
const textFields=computed<Field[]>(()=>[{key:(kind.value==='certificates'?'name':'title')+locale.value,label:locale.value==='Zh'?'中文标题 / 名称':'English title / name',max:200},...(['articles','cases'].includes(kind.value)?[{key:'summary'+locale.value,label:locale.value==='Zh'?'中文摘要':'English summary',type:'textarea',max:10000},{key:'seoTitle'+locale.value,label:'SEO 标题',max:200},{key:'seoDescription'+locale.value,label:'SEO 描述',type:'textarea',max:500}]:[])])
async function load(){ready.value=false;busy.value=true;error.value='';try{Object.keys(model).forEach(k=>delete model[k]);Object.assign(model,contentDefaults(kind.value));if(route.params.id!=='new')Object.assign(model,unwrapContent(await api.get(`/${kind.value}/${route.params.id}`)));if(kind.value==='articles')categories.value=(await api.get('/article-categories')).filter((c:any)=>c.status==='ACTIVE');if(kind.value==='cases'){const [p,c]=await Promise.all([api.get('/products'),api.get('/categories/tree')]);products.value=p;categories.value=flattenCategories(c)}await draft.restore();ready.value=true}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function save(status:string){if(!ready.value||!form.value?.reportValidity())return;if(status==='PUBLISHED'&&!await confirmAction('发布后符合语言及公开权限的内容将在网站显示。','发布内容','确认发布'))return;if(model.status==='PUBLISHED'&&status!=='PUBLISHED'&&!await confirmAction('此内容将从公开网站隐藏。','变更发布状态','确认保存'))return;busy.value=true;error.value='';try{const body={...model,status};const data=model.id?await api.put(`/${kind.value}/${model.id}`,body):await api.post(`/${kind.value}`,body);Object.assign(model,unwrapContent(data));draft.saved();message.value='内容已保存。';if(route.params.id==='new')await router.replace(`/${kind.value}/${model.id}`)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
onMounted(load);watch(()=>route.fullPath,load)
</script>
<template><section><RouterLink :to="`/${kind}`">返回{{contentLabels[kind]}}</RouterLink><div class="page-heading"><h1>{{model.id?'编辑':'新增'}}{{contentLabels[kind]}}</h1><span>{{statusNames[model.status]}} · 英文{{englishNames[model.englishStatus]}}</span></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="message" role="status">{{message}}</p><p v-if="busy" role="status">正在处理…</p><p v-if="draft.dirty.value" class="muted">有未保存的修改<span v-if="draft.lastSaved.value"> · 本机草稿 {{new Date(draft.lastSaved.value).toLocaleTimeString()}}</span></p>
<form ref="form" @submit.prevent="save('DRAFT')"><fieldset class="form-reset" :disabled="busy||!ready"><section class="surface"><h2>公共信息</h2><FormFields :model="model" :fields="shared"/><MediaField v-model="model.coverImage" label="上传封面"/><MediaField v-if="['certificates','catalogs'].includes(kind)" v-model="model.fileUrl" label="上传 PDF 文件" pdf @media="model.mediaId=$event"/><label v-if="kind==='catalogs'" class="form-stack">PDF 地址（必填）<input v-model="model.fileUrl" type="url" required></label></section>
<section class="surface"><h2>双语内容</h2><div class="tabs" aria-label="编辑语言"><button type="button" :aria-pressed="locale==='Zh'" @click="locale='Zh'">中文内容</button><button type="button" :aria-pressed="locale==='En'" @click="locale='En'">English</button></div><FormFields :model="model" :fields="textFields"/>
<div v-if="kind!=='catalogs'" class="form-footer"><h3>{{locale==='Zh'?'正文 / 说明':'English content'}}</h3><RichTextEditor :key="kind+locale" v-model="model[(kind==='certificates'?'description':'content')+locale]" :label="locale==='Zh'?'中文正文':'English content'" :disabled="busy"/></div>
<template v-if="kind==='cases'"><div v-for="[key,label] in [['applicationScene','应用场景'],['requirement','简要需求'],['solution','解决方式']]" :key="key" class="form-footer"><h3>{{label}} {{locale==='En'?'English':''}}</h3><RichTextEditor :key="key+locale" v-model="model[key+locale]" :label="label+locale" :disabled="busy"/></div></template></section>
<section v-if="kind==='cases'" class="surface"><h2>关联产品与分类</h2><div class="form-grid"><label>关联产品（可多选）<select multiple v-model="model.productIds" size="7"><option v-for="p in products" :key="p.id" :value="p.id">{{p.productCode}} · {{p.nameZh}}</option></select></label><label>关联分类（可多选）<select multiple v-model="model.categoryIds" size="7"><option v-for="c in categories" :key="c.id" :value="c.id">{{c.label}}</option></select></label></div><p class="muted small">桌面按住 Ctrl / Command 可多选。图片按上传顺序排列。</p><MediaField label="添加案例图片" @update:model-value="model.imageUrls.push($event)"/><ul><li v-for="(url,i) in model.imageUrls" :key="url">{{url}} <button type="button" @click="model.imageUrls.splice(i,1)">移除</button></li></ul></section>
<section class="surface"><h2>保存与发布</h2><p class="muted">英文内容必须人工确认。保存草稿不会公开。</p><div class="actions"><el-button :disabled="busy" @click="save('DRAFT')">保存草稿</el-button><el-button type="primary" :loading="busy" @click="save('PUBLISHED')">发布内容</el-button><el-button v-if="model.status==='PUBLISHED'" @click="save('OFFLINE')">保存并下架</el-button></div></section></fieldset></form><EnglishReview :type="({articles:'ARTICLE',cases:'CASE',certificates:'CERTIFICATE',catalogs:'CATALOG'} as Record<string,string>)[kind]!" :model="model" :dirty="draft.dirty.value" :busy="busy" @changed="load"/></section></template>
