<script setup lang="ts">
import {safeUrl} from '../utils/site'
const props=defineProps<{kind:string}>(),route=useRoute(),{t,link,locale}=useLocale()
const {data,unavailable,alternateAvailable}=await useContent(()=>'/public/'+props.kind+'/'+encodeURIComponent(String(route.params.slug)))
usePageSeo(()=>({title:data.value?.seoTitle||data.value?.title,description:data.value?.seoDescription||data.value?.summary,image:data.value?.coverImage,type:props.kind==='articles'?'Article':undefined,item:data.value,alternate:alternateAvailable.value,noindex:unavailable.value}))
</script>
<template><LocaleUnavailable v-if="unavailable" :locale="locale" :path="route.fullPath"/><main v-else-if="data" class="wrap section content-detail"><nav class="breadcrumb"><NuxtLink :to="link('/'+kind)">{{kind==='cases'?t('应用案例','Applications'):t('新闻资讯','News')}}</NuxtLink> / {{data.title}}</nav><h1>{{data.title}}</h1><time v-if="data.publishedAt" :datetime="data.publishedAt">{{data.publishedAt.slice(0,10)}}</time><p v-if="data.summary" class="lead">{{data.summary}}</p><SiteImage v-if="safeUrl(data.coverImage)" class="company-image" :src="safeUrl(data.coverImage)" :alt="data.title" width="1200" height="700" loading="eager" fetchpriority="high"/><div v-if="data.content" class="prose" v-html="data.content"/>
  <template v-if="kind==='cases'"><section v-for="field in [{key:'applicationScene',zh:'应用场景',en:'Application'},{key:'requirement',zh:'需求',en:'Requirement'},{key:'solution',zh:'解决方案',en:'Solution'}]" :key="field.key" class="detail-section"><template v-if="data[field.key]"><h2>{{t(field.zh,field.en)}}</h2><div class="prose" v-html="data[field.key]"/></template></section><div v-if="data.imageUrls?.length" class="content-grid"><SiteImage v-for="url in data.imageUrls" :key="url" :src="safeUrl(url)" :alt="data.title" width="640" height="430" loading="lazy"/></div><section v-if="data.products?.length" class="detail-section"><h2>{{t('相关产品','Related products')}}</h2><ul><li v-for="p in data.products" :key="p.slug"><NuxtLink :to="link('/products/'+p.slug)">{{p.name}}</NuxtLink></li></ul></section></template>
</main></template>
