<script setup lang="ts">
import {safeUrl} from '../utils/site'
const props=defineProps<{product:any;related?:any[]}>(),{t,link,locale}=useLocale(),selected=ref(0)
watch(()=>props.product?.slug,()=>selected.value=0)
const images=computed(()=>props.product.images?.length?props.product.images:props.product.coverImage?[{url:props.product.coverImage,alt:props.product.name}]:[])
const active=computed(()=>images.value[selected.value]||images.value[0])
const value=(a:any)=>a.options?.length?a.options.map((o:any)=>o.label||o.valueCode).join(' / '):a.value??a.numericValue??'—'
</script>
<template><main class="wrap section" v-if="product">
  <nav class="breadcrumb"><NuxtLink :to="link('/products')">{{t('产品中心','Products')}}</NuxtLink> / <span>{{product.name}}</span></nav>
  <div class="detail-top"><section :aria-label="t('产品图片','Product images')"><SiteImage v-if="safeUrl(active?.url)" class="detail-image" :src="safeUrl(active.url)" :alt="active.alt||product.name" width="900" height="675" loading="eager" fetchpriority="high"/><div v-else class="product-image-empty detail-image">{{t('产品图片待补充','Product image not available')}}</div><div v-if="images.length>1" class="gallery-thumbs"><button v-for="(image,i) in images" :key="image.url" :aria-label="t('查看图片 '+(i+1),'View image '+(i+1))" :aria-pressed="selected===i" @click="selected=i"><SiteImage :src="safeUrl(image.url)" :alt="image.alt||product.name" width="100" height="75" loading="lazy"/></button></div></section>
    <section><p class="eyebrow">{{product.productCode}}</p><h1>{{product.name}}</h1><p v-if="locale!=='en'&&product.secondaryName" class="secondary-name">{{product.secondaryName}}</p><p>{{product.summary}}</p><dl class="core-params"><template v-for="a in product.attributes?.slice(0,6)" :key="a.code"><dt>{{a.name}}</dt><dd>{{value(a)}} {{a.unit}}</dd></template></dl><NuxtLink class="button primary" :to="link('/contact')">{{t('咨询此产品','Enquire about this product')}}</NuxtLink></section></div>
  <section v-if="product.description" class="detail-section"><h2>{{t('产品详情与应用','Product details and applications')}}</h2><div class="prose" v-html="product.description"/></section>
  <section v-if="product.attributes?.length" class="detail-section"><h2>{{t('技术参数','Technical specifications')}}</h2><div class="table-scroll" tabindex="0" :aria-label="t('技术参数表','Technical specification table')"><table><tbody><tr v-for="a in product.attributes" :key="a.code"><th scope="row">{{a.name}}</th><td>{{value(a)}} {{a.unit}}</td></tr></tbody></table></div></section>
  <section v-if="product.variants?.length" class="detail-section"><h2>{{t('产品规格','Product variants')}}</h2><div class="table-scroll" tabindex="0"><table><thead><tr><th>{{t('规格编号','Variant code')}}</th><th>{{t('名称','Name')}}</th><th>{{t('参数','Specifications')}}</th></tr></thead><tbody><tr v-for="v in product.variants" :key="v.variantCode"><th scope="row">{{v.variantCode}}</th><td>{{v.name}}</td><td><span v-for="a in v.values" :key="a.code" class="variant-value">{{a.name}}: {{value(a)}} {{a.unit}}</span></td></tr></tbody></table></div></section>
  <section v-if="product.publicAttachments?.length" class="detail-section"><h2>{{t('产品资料','Product documents')}}</h2><ul class="document-list"><li v-for="a in product.publicAttachments" :key="a.downloadUrl"><a v-if="safeUrl(a.downloadUrl)" :href="safeUrl(a.downloadUrl)" target="_blank" rel="noopener">{{a.title}} <span>{{a.fileType}} ↗</span></a></li></ul></section>
  <section v-if="product.relatedCases?.length" class="detail-section"><h2>{{t('应用案例','Application cases')}}</h2><div class="content-grid"><NuxtLink v-for="c in product.relatedCases" :key="c.slug" :to="link('/cases/'+c.slug)"><h3>{{c.title}}</h3><p>{{c.summary}}</p></NuxtLink></div></section>
  <section v-if="related?.length" class="detail-section"><h2>{{t('相关产品','Related products')}}</h2><div class="product-grid"><ProductCard v-for="p in related" :key="p.slug" :product="p" :locale="locale"/></div></section>
</main></template>
