<script setup lang="ts">
const props=defineProps<{open:boolean}>(),emit=defineEmits<{close:[]}>(),{t,link,locale}=useLocale(),keyword=ref(''),rows=ref<any[]>([]),busy=ref(false),error=ref(''),config=useRuntimeConfig();let timer:ReturnType<typeof setTimeout>,generation=0
watch(keyword,(value:string)=>{clearTimeout(timer);const current=++generation;error.value='';rows.value=[];busy.value=false;if(!value.trim())return;timer=setTimeout(async()=>{busy.value=true;try{const result=await $fetch<any>('/public/search/suggestions',{baseURL:config.public.apiBase,query:{q:value.trim()},headers:{'Accept-Language':locale.value}});if(current===generation)rows.value=result.data.map((row:any)=>({...row,name:row.label}))}catch{if(current===generation)error.value=t('联想暂时不可用，可按回车搜索。','Suggestions are unavailable. Press Enter to search.')}finally{if(current===generation)busy.value=false}},300)})
watch(()=>props.open,(open:boolean)=>{if(!open){clearTimeout(timer);generation++;busy.value=false}});onBeforeUnmount(()=>{clearTimeout(timer);generation++})
async function search(){if(!keyword.value.trim())return;emit('close');await navigateTo({path:link('/search'),query:{keyword:keyword.value.trim()}})}
</script>
<style scoped>
.search-form{gap:10px;align-items:stretch;border-bottom:0}
.search-form input{flex:1 1 0;width:0;min-width:0;min-height:48px;border:1px solid var(--silver);border-radius:4px;font-size:16px}
.search-form .button{flex:0 0 auto;white-space:nowrap;word-break:normal;min-height:48px;padding:12px 20px;border-radius:4px;line-height:1.5}
.suggestions strong{font-size:16px;line-height:1.5;overflow-wrap:anywhere}
.suggestions span{overflow-wrap:anywhere}
</style>
<template><OverlayPanel :open="open" :label="t('搜索产品','Search products')" kind="search-panel" @close="emit('close')"><div class="panel-heading"><h2>{{t('查找产品','Find a product')}}</h2><button class="icon-button" :aria-label="t('关闭搜索','Close search')" @click="emit('close')"><svg viewBox="0 0 24 24" width="22" height="22" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m6 6 12 12M6 18 18 6"/></svg></button></div><p class="muted">{{t('输入产品名称、编号、材质或标准。','Search by product name, code, material or standard.')}}</p><form class="search-form" @submit.prevent="search"><label class="sr-only" for="search-keyword">{{t('搜索关键词','Search keyword')}}</label><input id="search-keyword" v-model="keyword" autofocus maxlength="200" :placeholder="t('搜索产品','Search products')"><button class="button" type="submit">{{t('搜索','Search')}}</button></form><p v-if="busy" role="status" class="notice">{{t('正在查找…','Searching…')}}</p><p v-if="error" role="status" class="notice">{{error}}</p><ul v-if="rows.length" class="suggestions"><li v-for="row in rows" :key="row.slug"><NuxtLink :to="link('/products/'+row.slug)" @click="emit('close')"><strong>{{row.name}}</strong><span>{{row.productCode}}</span></NuxtLink></li></ul><p v-else-if="keyword&&!busy&&!error" class="notice">{{t('按回车查看全部搜索结果。','Press Enter to view all results.')}}</p></OverlayPanel></template>
