CREATE TABLE catalog_primary_guard (id INT PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO catalog_primary_guard(id) VALUES (1);
CREATE TABLE certificate (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    name_zh VARCHAR(200) NOT NULL,
    name_en VARCHAR(200) NULL,
    description_zh TEXT NULL,
    description_en TEXT NULL,
    english_status VARCHAR(16) NOT NULL DEFAULT 'EMPTY',
    cover_image VARCHAR(2048) NULL,
    media_id BIGINT NULL,
    file_url VARCHAR(2048) NULL,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    allow_download BOOLEAN NOT NULL DEFAULT FALSE,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    FOREIGN KEY(media_id) REFERENCES media_file(id),
    CHECK(english_status IN ('EMPTY','AI_DRAFT','CONFIRMED')),
    CHECK(status IN ('DRAFT','PUBLISHED','OFFLINE')),
    CHECK(is_public IN (0,1) AND allow_download IN (0,1) AND is_featured IN (0,1)),
    CHECK(sort_order>=0),
    KEY idx_certificate_public(is_public,status,deleted_at,sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE catalog (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title_zh VARCHAR(200) NULL,
    title_en VARCHAR(200) NULL,
    language_mode VARCHAR(16) NOT NULL,
    english_status VARCHAR(16) NOT NULL DEFAULT 'EMPTY',
    version VARCHAR(100) NOT NULL,
    cover_image VARCHAR(2048) NULL,
    media_id BIGINT NULL,
    file_url VARCHAR(2048) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    primary_zh TINYINT GENERATED ALWAYS AS (CASE WHEN is_primary=1 AND status='PUBLISHED' AND deleted_at IS NULL AND language_mode IN ('ZH_ONLY','BILINGUAL') THEN 1 ELSE NULL END) STORED,
    primary_en TINYINT GENERATED ALWAYS AS (CASE WHEN is_primary=1 AND status='PUBLISHED' AND deleted_at IS NULL AND language_mode IN ('EN_ONLY','BILINGUAL') THEN 1 ELSE NULL END) STORED,
    UNIQUE KEY uk_catalog_primary_zh(primary_zh),
    UNIQUE KEY uk_catalog_primary_en(primary_en),
    FOREIGN KEY(media_id) REFERENCES media_file(id),
    CHECK(language_mode IN ('ZH_ONLY','EN_ONLY','BILINGUAL')),
    CHECK(english_status IN ('EMPTY','AI_DRAFT','CONFIRMED')),
    CHECK(status IN ('DRAFT','PUBLISHED','OFFLINE')),
    CHECK(is_primary IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
